runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: img
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest
- name: PIL
  version: latest